In [6]:
import requests
from datetime import datetime
import pandas as pd

In [7]:
def fetch_sensor_readings(start: datetime, end: datetime, limit: int = 10000):
    """
    Calls the /sensor-readings/range endpoint and returns the JSON response.

    Args:
        start (datetime): Start datetime (inclusive)
        end (datetime): End datetime (exclusive)
        limit (int): Maximum number of points to return

    Returns:
        list or dict: Parsed JSON response from the API
    """
    url = "http://localhost:8000/sensor-readings/range"
    
    params = {
        "start": start.isoformat(),
        "end": end.isoformat(),
        "limit": limit,
    }

    response = requests.get(url, params=params)
    response.raise_for_status()

    data = response.json()

    # If no data, return empty df
    if not data:
        return pd.DataFrame()

    # Convert to DataFrame
    df = pd.DataFrame(data)

    return df

In [8]:
data = fetch_sensor_readings(
    start=datetime(2025, 11, 1, 0, 0, 0),
    end=datetime(2025, 11, 15, 0, 0, 0),
    limit=5000
)

In [9]:

data

,sensor_name,variable,value,timestamp,flagged,location_wkt,sensor_centroid_longitude,ground_height_above_sea_level,sensor_centroid_latitude,sensor_height_above_ground,broker_name,raw_id
0,PER_AIRMON_MESH306245,PM10,12.05000,2025-11-01T00:00:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521
1,PER_AIRMON_MESH306245,PM1,4.59000,2025-11-01T00:00:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521
2,PER_PEOPLE_NCLHEBERST_EAST_TO_WEST,Walking,25.00000,2025-11-01T00:00:00,False,POINT(-1.623428 54.973557),-1.623428,66.000000,54.973557,2.0,People Counting API,80377
3,PER_AIRMON_MESH306245,PM2.5,6.44000,2025-11-01T00:00:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521
4,PER_AIRMON_MESH306245,PM 4,8.86000,2025-11-01T00:00:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,PER_PEOPLE_NCLHEBERST_WEST_TO_EAST,Walking,36.00000,2025-11-02T15:30:00,False,POINT(-1.623428 54.973557),-1.623428,66.000000,54.973557,2.0,People Counting API,80379
4996,PER_PEOPLE_NCLHEBERST_EAST_TO_WEST,Walking,14.00000,2025-11-02T15:30:00,False,POINT(-1.623428 54.973557),-1.623428,66.000000,54.973557,2.0,People Counting API,80377
4997,PER_AIRMON_MESH306245,NO,2.53125,2025-11-02T15:30:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521
4998,PER_AIRMON_MESH306245,PM2.5,2.74000,2025-11-02T15:30:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521
4999,PER_AIRMON_MESH306245,PM1,1.60000,2025-11-02T15:30:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521

In [11]:
data_filtered = data[data["sensor_name"]=="PER_AIRMON_MESH306245"]

In [12]:
data_filtered.head()

,sensor_name,variable,value,timestamp,flagged,location_wkt,sensor_centroid_longitude,ground_height_above_sea_level,sensor_centroid_latitude,sensor_height_above_ground,broker_name,raw_id
0,PER_AIRMON_MESH306245,PM10,12.05000,2025-11-01T00:00:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521
1,PER_AIRMON_MESH306245,PM1,4.59000,2025-11-01T00:00:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521
3,PER_AIRMON_MESH306245,PM2.5,6.44000,2025-11-01T00:00:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521
4,PER_AIRMON_MESH306245,PM 4,8.86000,2025-11-01T00:00:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521
5,PER_AIRMON_MESH306245,NO2,103.07664,2025-11-01T00:00:00,False,POINT(-1.648605 54.977836),-1.648605,111.389999,54.977836,2.0,aq_mesh_api,79521